### ISSUE TITLE
Upgrade to 2.9.0 causes Android build failure: java.lang.NoClassDefFoundError: com/google/android/exoplayer2/upstream/Loader$Callback

### ISSUE THREAD

**Issue by haohighview** [martijn00/ExoPlayerXamarin#75] opened 2018-10-12 12:14 UTC
added `"<AndroidEnableDesugar>true<AndroidEnableDesugar>"`

1>Exception in thread "main" java.lang.NoClassDefFoundError: com/google/android/exoplayer2/upstream/Loader$Callback
1>	at java.lang.ClassLoader.defineClass1(Native Method)
1>	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
1>	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
1>	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:66)
1>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
1>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
1>	at com.google.devtools.build.android.desugar.LambdaDesugaring.loadFromInternal(LambdaDesugaring.java:330)
1>	at com.google.devtools.build.android.desugar.LambdaDesugaring.access$500(LambdaDesugaring.java:53)
1>	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.createLookup(LambdaDesugaring.java:559)
1>	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:395)
1>	at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
1>	at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
1>	at org.objectweb.asm.ClassReader.a(Unknown Source)
1>	at org.objectweb.asm.ClassReader.b(Unknown Source)
1>	at org.objectweb.asm.ClassReader.accept(Unknown Source)
1>	at org.objectweb.asm.ClassReader.accept(Unknown Source)
1>	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)

**Comment by martijn00** [comment] 2018-10-12 12:18
Related to https://github.com/martijn00/ExoPlayerXamarin/issues/74#issuecomment-425655112

We've got to wait for Microsoft to fix this.

**Comment by dupuisdavid** [comment] 2018-10-21 16:04
Meanwhile, what about the idea to retreat to exoplayer version 2.8.8?

**Comment by martijn00** [comment] 2018-10-21 16:42
Yes 2.8.8 works fine for me for now.

**Comment by martijn00** [comment] 2018-12-07 13:22
Closed as duplicate of #74

**Closed by martijn00** 2018-12-07 13:22 UTC
