### ISSUE TITLE
Get movie info like a movie link from EditText

### ISSUE THREAD

**Issue by karishma200** [martijn00/ExoPlayerXamarin#73] opened 2018-09-06 13:23 UTC
Hi, I want to copy the movie Url link manually in EditText.
 And Media.exolist.json file full of Assets I remove sample. 
And use the play button to play the movie. 
Like the link below
 https://play.google.com/store/apps/details?id=com.stream.video.exoplayer 
 Please send me an example for my email : ma0528160@gmail.com 
Or guide me.
Thankful

**Comment by martijn00** [comment] 2018-09-06 13:35
Duplicate of https://github.com/martijn00/ExoPlayerXamarin/issues/72

**Closed** 2018-09-06 13:35 UTC
